#!/bin/bash
set -e

if ! dpkg -l puppetlabs-release >/dev/null; then
  TMPFILE=$(mktemp)
  wget -qO ${TMPFILE} http://apt.puppetlabs.com/puppetlabs-release-precise.deb
  dpkg -i ${TMPFILE}
  rm ${TMPFILE}
  apt-get update -qq
fi

apt-get install -y -qq --no-upgrade ruby1.9.1 puppet='3.2.*' puppet-common='3.2.*' rubygems
gem install --no-ri --no-rdoc hiera-eyaml hiera-eyaml-gpg

mkdir -p /etc/puppet /etc/puppet/keys
chown -R puppet:puppet /etc/puppet
chmod 700 /etc/puppet/keys

if [ -a /vagrant/tools/keys/pubring.gpg ]
  then
    cp -Rf /vagrant/tools/keys/* /etc/puppet/keys
fi

chown -R puppet:puppet /etc/puppet/keys
