#!/bin/bash
set -e

cd "$(dirname "$0")/.."
bundle install --path vendor/gems
sudo bundle exec puppet apply \
  --hiera_config hiera.yaml \
  --manifestdir manifests \
  --modulepath modules:vendor/modules \
  manifests/site.pp \
  $@
